# mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/board
spring.datasource.username=admin
spring.datasource.password=mysql188
mybatis.mapper-locations=classpath:com.fastcampus.boardserver.mapper/*.xml

# redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.password=
spring.data.redis.repositories.enabled=false
expire.defaultTime=36288000
spring.data.redis.database=0

# ?? ??? ?? ??
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG
logging.level.org.springframework.data.redis.cache=TRACE